# Generated by Django 4.1.1 on 2022-09-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewAdmin',
            new_name='myAdmin',
        ),
    ]
