# Generated by Django 4.1.1 on 2022-09-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_newadmin_myadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myAdmin',
        ),
    ]
